name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker BuildKit
        run: |
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Create .env file from secret
        run: echo "${{ secrets.DOTENV_FILE }}" > .env

      - name: Show .env content for debugging
        run: cat .env

      - name: Build Docker image
        run: docker build -t teatrodelembuste .

      - name: Tag Docker image
        run: |
          docker tag teatrodelembuste:latest ${{ secrets.DOCKERHUB_USERNAME }}/teatrodelembuste:latest
          docker tag teatrodelembuste:latest ${{ secrets.DOCKERHUB_USERNAME }}/teatrodelembuste:${{ steps.vars.outputs.sha_short }}

      - name: Push Docker image (latest + SHA)
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/teatrodelembuste:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/teatrodelembuste:${{ steps.vars.outputs.sha_short }}

      - name: Show Docker image size
        run: docker images | grep teatrodelembuste
